add microsoft-mimalloc to dependences
PKUHPC/CraneSched pull request #242
Opened 2024-03-18 10:25 UTC by ahz-r3v

2024-03-22 14:22 UTC, RileyWen commented on dependencies/cmake/mimalloc/CMakeLists.txt
> +if (BUILD_SHARED_LIBS)
这个在mialloc这个包里有作用吗

2024-03-22 14:22 UTC, RileyWen commented on dependencies/cmake/mimalloc/CMakeLists.txt
> +    # TODO
这地方可以删了

2024-03-22 14:22 UTC, RileyWen commented on dependencies/cmake/mimalloc/CMakeLists.txt
> +FetchContent_GetProperties(mimalloc)
已经makeavailable了 这个GetProperties和find package还有必要吗

2024-03-22 14:22 UTC, RileyWen commented on dependencies/cmake/mimalloc/CMakeLists.txt
而且mialloc正常需要overload new operator，应该是要include一个头文件的，这边没有看到？

2024-03-25 03:12 UTC, ahz-r3v commented on dependencies/cmake/mimalloc/CMakeLists.txt
> +if (BUILD_SHARED_LIBS)
已修改

2024-03-25 03:12 UTC, ahz-r3v commented on dependencies/cmake/mimalloc/CMakeLists.txt
> +    # TODO
已修改

2024-03-25 03:12 UTC, ahz-r3v commented on dependencies/cmake/mimalloc/CMakeLists.txt
> +FetchContent_GetProperties(mimalloc)
已修改

2024-03-25 10:10 UTC, RileyWen requested changes

2024-03-25 10:10 UTC, RileyWen commented on dependencies/cmake/mimalloc/CMakeLists.txt
> +find_package(mimalloc REQUIRED CONFIG)
这个应该可以不用吧

2024-03-25 10:10 UTC, RileyWen commented on dependencies/cmake/mimalloc/CMakeLists.txt
> +    set(MMLC_SRC_URL "https://gitee.com/zenglingbo/crane-sched-deps/blob/master/mimalloc-v1.8.2.zip")
这个gitee source也可以不用

2024-03-25 10:24 UTC, ahz-r3v commented on dependencies/cmake/mimalloc/CMakeLists.txt
> +find_package(mimalloc REQUIRED CONFIG)
已修改

2024-03-25 10:25 UTC, ahz-r3v commented on dependencies/cmake/mimalloc/CMakeLists.txt
> +    set(MMLC_SRC_URL "https://gitee.com/zenglingbo/crane-sched-deps/blob/master/mimalloc-v1.8.2.zip")
我看其他的依赖都有一个gitee的源，专门让马老师上传了一份到gitee

2024-11-19 02:53 UTC, closed without merging

2024-11-19 02:54 UTC, RileyWen commented
Moved to #364