Separate Authentication and Modification in AccountManager
PKUHPC/CraneSched pull request #321
Opened 2024-09-02 08:28 UTC by huerni

2024-09-20 09:07 UTC, RileyWen requested changes

2024-09-23 01:26 UTC, huerni commented on src/CraneCtld/AccountManager.cpp
> +    return Result{false, fmt::format("Unknown account '{}'", object_account)};
ok

2024-09-25 10:09 UTC, RileyWen commented on src/CraneCtld/AccountManager.h
> +#include "crane/expected.h"
这个就是标准库的 <expected>

2024-09-26 01:28 UTC, huerni commented on src/CraneCtld/AccountManager.h
> +#include "crane/expected.h"
我这里试了第三方库 https://github.com/TartanLlama/expected，和标准库的用法差不多。这个可以直接复制头文件使用。clang17对c++23的支持好像有问题。升级到23 clang版本可能要升级到18

2024-10-24 03:57 UTC, RileyWen commented on protos/PublicDefs.proto
> +enum ErrCode {
这个错误码和public header里面的得看看怎么统一下

2024-10-25 03:04 UTC, L-Xiafeng commented on src/CraneCtld/AccountManager.cpp
> +AccountManager::SuccessOrErrCode AccountManager::CheckOperatorPrivilegeHigher(
这个是不是该叫SameOrHigher？
还有IsOperatorPrivilegeSameAndHigher这个函数

2024-10-25 03:10 UTC, huerni commented on src/CraneCtld/AccountManager.cpp
> +AccountManager::SuccessOrErrCode AccountManager::CheckOperatorPrivilegeHigher(
CheckOperatorPrivilegeHigher  这个函数 权限相等会返回ERR_PERMISSION_USER，只能权限高于User
IsOperatorPrivilegeSameAndHigher 这个可以改成SameOrHigher，same或者higher都返回true

2024-10-25 03:26 UTC, L-Xiafeng commented on src/CraneCtld/AccountManager.cpp
> +    auto result = CheckPartitionIsAllowed(find_account, object_account,
前面也有一个result，要不前面那个加个大括号，或者提前声明这个变量？拿结果的时候直接result=xxx不要auto

2024-10-25 03:29 UTC, L-Xiafeng commented on src/CraneCtld/AccountManager.cpp
> +      if (std::find(find_parent->allowed_partition.begin(),
std::find可以用新的ranges::find(find_parent->allowed_partition,par)替换掉，好看一点

2024-10-25 03:30 UTC, L-Xiafeng commented on src/CraneCtld/AccountManager.cpp
> +  for (auto&& [partition, qos] : new_user.account_to_attrs_map[object_account]
这里auto&&要不替换成const auto&，统一下风格

2024-10-25 03:37 UTC, huerni commented on src/CraneCtld/AccountManager.cpp
> +    auto result = CheckPartitionIsAllowed(find_account, object_account,
好

2024-10-25 03:39 UTC, RileyWen commented on src/CraneCtld/AccountManager.cpp
> +      if (std::find(find_parent->allowed_partition.begin(),
ranges：：contains 吧

2024-10-25 04:40 UTC, L-Xiafeng commented on src/CraneCtld/AccountManager.cpp
> +  return AddUser_(find_user, find_account, std::move(new_user));
这里move是为什么？这个函数为什么要用右值引用参数？换成const &会不会好一点

2024-10-25 05:31 UTC, huerni commented on src/CraneCtld/AccountManager.cpp
> +  return AddUser_(find_user, find_account, std::move(new_user));
我是沿用之前的代码，少了复制，不过换成const &确实更安全

2024-10-29 07:55 UTC, L-Xiafeng commented
我没啥问题了。但是函数返回值，现在这样其实和直接返回一个int没区别，std::expected好像有点多余，看 @RileyWen 有没有什么意见？

2024-10-29 17:56 UTC, RileyWen commented
我明天看下

2024-11-01 14:28 UTC, RileyWen requested changes

2024-11-01 14:28 UTC, RileyWen commented on src/CraneCtld/AccountManager.cpp
> +    const std::string& name, const User::AdminLevel& new_level) {
这个AdminLevel本身就是个integer，不需要传引用

2024-11-01 14:28 UTC, RileyWen commented on src/CraneCtld/AccountManager.cpp
> +  // return Result{true};
不用的注释删掉

2024-11-01 14:28 UTC, RileyWen commented on src/CraneCtld/AccountManager.cpp
> +  const std::string name = user.name;
const T&

2024-11-01 14:28 UTC, RileyWen commented on src/CraneCtld/AccountManager.cpp
> +        "in "
这种行稍微整理下

2024-11-01 14:28 UTC, RileyWen commented on src/CraneCtld/AccountManager.cpp
> +  const std::string name = user.name;
这种还有好多处 都检查下

2024-11-01 14:28 UTC, RileyWen commented on src/CraneCtld/AccountManager.cpp
> +    const Account* account_ptr, const std::string& account,
account这种多余参数也都检查下，然后把前面重名的account_ptr命名为account

2024-11-04 13:03 UTC, RileyWen commented on src/CraneCtld/AccountManager.h
> +      const User* user, const Account* account_ptr, const std::string& account,
这边的account_ptr和account有冗余和重复吗

2024-11-04 13:05 UTC, RileyWen commented on src/CraneCtld/AccountManager.h
> +                                      const User::AdminLevel new_level);
这种enum type实际上是int 不需要const，const int 和int没区别

2024-11-04 13:10 UTC, RileyWen commented on src/CraneCtld/AccountManager.cpp
> +                                                const std::string& partition) {
这边account没有用呀 还有个函数也是这样

2024-11-04 13:10 UTC, RileyWen commented on src/CraneCtld/AccountManager.cpp
> +                                                const std::string& partition) {
这个地方没查完

2024-11-04 13:13 UTC, RileyWen commented on src/CraneCtld/AccountManager.cpp
> +  if (user->account_to_attrs_map.at(account).allowed_partition_qos_map.contains(
这个地方换成account->name看看可以吗 函数参数实际上是重复的

2024-11-04 13:20 UTC, RileyWen requested changes

2024-11-04 13:20 UTC, RileyWen commented on src/CraneCtld/AccountManager.h
> +  CraneExpected<bool> CheckAddAccountAllowedPartition(
account_ptr

2024-11-04 13:20 UTC, RileyWen commented on src/CraneCtld/AccountManager.h
> +                                             const Account* account_ptr,
account_ptr

2024-11-04 13:20 UTC, RileyWen commented on src/CraneCtld/AccountManager.h
> +      const User* user, const Account* account_ptr, const std::string& account,
account_ptr

2024-11-04 13:23 UTC, RileyWen commented on protos/PublicDefs.proto
> +// Note: UserInfo DIFFERS from the `User` struct in C++ code and database
这边是开了什么自动格式化吗 这边的排版本来是手动调的 自动化格式化完反而有些乱了

2024-11-04 13:32 UTC, RileyWen commented on src/CraneCtld/AccountManager.cpp
> +  return true;
CraneExpected<bool>全局替换成CraneExpected<void>
return true; 全局替换成 return {};

2024-11-04 13:35 UTC, RileyWen commented on src/CraneCtld/AccountManager.cpp
> +AccountManager::CraneExpected<bool> AccountManager::CheckSetUserAdminLevel(
ChechValidityOfAdminLevel

2024-11-04 13:36 UTC, RileyWen commented on src/CraneCtld/AccountManager.cpp
> +AccountManager::CraneExpected<bool> AccountManager::CheckSetUserAdminLevel(
这个函数没用到user呀 这种函数查一下吧 参数无用的情况太多了

2024-11-04 13:37 UTC, RileyWen commented on src/CraneCtld/AccountManager.cpp
> +  const std::string& name = user.name;
这个也是一样 要不你开个自动化检查吧 看看clang tidy能不能辅助查找下 这种无用变量也很多

2024-11-05 01:21 UTC, huerni commented on src/CraneCtld/AccountManager.cpp
> +                                                const std::string& partition) {
还在改  还没改完

2024-11-05 01:23 UTC, huerni commented on src/CraneCtld/AccountManager.h
> +      std::string account, const std::string& value, bool force);
emm最开始的代码就是这样  account可能传入空，需要赋值为default_account

2024-11-05 01:27 UTC, huerni commented on src/CraneCtld/AccountManager.cpp
> +  if (user->account_to_attrs_map.at(account).allowed_partition_qos_map.contains(
可以的，有几处是这样，我都改下

2024-11-05 02:11 UTC, huerni commented on protos/PublicDefs.proto
> +// Note: UserInfo DIFFERS from the `User` struct in C++ code and database
可能是，自动调整了

2024-11-05 14:16 UTC, RileyWen commented on src/CraneCtld/AccountManager.h
> +      std::string account, const std::string& value, bool force);
emmm 我是说你这个参数应该是const std::string&

2024-11-05 14:26 UTC, RileyWen commented on src/CraneCtld/AccountManager.cpp
> +    bool is_user) {
这个is user实际上也没有意义？

2024-11-05 14:30 UTC, RileyWen commented on src/CraneCtld/AccountManager.cpp
> +        if (is_user)
这个地方is_user也是其实没啥必要

2024-11-05 14:35 UTC, RileyWen commented on src/CraneCtld/AccountManager.h
> +#include "range/v3/view/unique.hpp"
这个东西有用到吗

2024-11-05 14:38 UTC, RileyWen commented on protos/PublicDefs.proto
> +enum OperatorType {
重命名为OperationType，-or是人的词根后缀呀

2024-11-06 01:21 UTC, huerni commented on src/CraneCtld/AccountManager.cpp
> +    bool is_user) {
前端展示不同

2024-11-06 01:21 UTC, huerni commented on src/CraneCtld/AccountManager.cpp
> +        if (is_user)
前端展示，返回错误码不同

2024-11-07 15:29 UTC, RileyWen commented
看下最新的commit 有几个地方实现逻辑有错误 关于QoS的那几个 原有实现是对的 这个开个会讨论下

2024-11-07 15:32 UTC, RileyWen commented
重复接口太多了 精简后发现很多实现逻辑上的错误 标注FIXME的实现有问题 然后得查下类似的问题

2024-11-07 15:35 UTC, RileyWen commented
然后还是有些const int没改

2024-11-07 15:35 UTC, RileyWen commented
QoS那块鉴权你理解错了

2024-11-07 17:40 UTC, RileyWen commented
Uid在最外层就转换了 内层不要重复用uid去获取用户了

2024-11-08 01:42 UTC, huerni commented
> 然后存在很多一个用户获取两遍的情况

这种情况应该没有吧，内部获取是封装在一起了。有些外部不需要获取op_user，然后直接封装在内部函数了。所以有的用getuserbyuid在外部获取，有的在内部调用。基本上每个外部函数都只调用了一次GetUserInfoByUid

2024-11-08 02:28 UTC, huerni commented on src/CraneCtld/AccountManager.h
> +                                                 bool read_only_priv);
这两个逻辑不一样，合在一起的话，每个函数都要额外判断，这样会增加更多冗余代码，容易出错

2024-11-08 02:30 UTC, huerni commented on src/CraneCtld/AccountManager.cpp
> +  std::string actual_account = account.empty() ? p->default_account : account;
p->default_account之前必须判断p是否存在，如果放在外面的话，每个之前都得判断p是否存在

2024-11-11 14:07 UTC, RileyWen commented
AccountManager.cpp:ModifyDefaultQoS 重复加锁 查所有剩下的函数是否有重复枷锁

2024-11-11 14:08 UTC, RileyWen commented
存在加锁序错乱 会死锁 检查所有函数

2024-11-11 14:24 UTC, RileyWen commented
账户系统并发测试没跟上，有死锁情况没测出来

2024-11-11 14:27 UTC, RileyWen commented
clang19下spdlog编译有一大堆warning，clang20直接挂了，升级spdlog至最新

2024-11-11 14:28 UTC, RileyWen commented
内部未加锁函数统一增加NoLock后缀

2024-11-11 15:13 UTC, RileyWen commented
user->account_to_attrs_map.at 重复求值

2024-11-12 01:31 UTC, huerni commented
> AccountManager.cpp:ModifyDefaultQoS 重复加锁 查所有剩下的函数是否有重复枷锁

意外意外，昨天不小心一起复制过去了    其他的我再检查检查

2024-11-12 09:07 UTC, L-Xiafeng commented
开个asan/tsan本地测试下，看会不会有问题吧

2024-11-13 06:35 UTC, huerni commented
现在代码方面还有问题吗  没有问题的话就可以交给周老师重测了

2024-11-13 06:52 UTC, RileyWen commented
先测吧

2024-11-15 02:15 UTC, RileyWen commented on src/CraneCtld/AccountManager.cpp
> +        user.account_to_attrs_map.at(account).allowed_partition_qos_map.end()) {
user.account_to_attrs_map.at(account) 这个地方弄个引用

2024-11-15 02:49 UTC, RileyWen commented on src/CraneCtld/AccountManager.cpp
> +         user.account_to_attrs_map.at(account).allowed_partition_qos_map) {
user.account_to_attrs_map.at(account)

2024-11-15 02:49 UTC, RileyWen commented on src/CraneCtld/AccountManager.cpp
> +          res_account_map->try_emplace(m_account_map_.at(father)->name,
1

2024-11-21 03:12 UTC, merged