ipv6 support
PKUHPC/CraneSched pull request #322
Opened 2024-09-04 02:28 UTC by L-Xiafeng

2024-09-05 11:27 UTC, Nativu5 requested changes

2024-09-05 11:27 UTC, Nativu5 commented on src/Utilities/PublicHeader/Network.cpp
> +  /* For IPv6*/
```
/* For IPv6 */
```

2024-09-17 16:36 UTC, RileyWen commented on src/Misc/Pam/PamUtil.cpp
> +          std::string addr[4];
这个地方4是不是有点问题

2024-09-20 06:03 UTC, RileyWen approved these changes

2024-09-20 06:05 UTC, merged