Feat: Modify log modular output
PKUHPC/CraneSched pull request #341
Opened 2024-10-29 02:00 UTC by 1daidai1

cranectld
![image](https://github.com/user-attachments/assets/ae86998a-53a4-495f-836f-6440edb44705)
craned
![image](https://github.com/user-attachments/assets/85df01d6-0a72-4c51-88cb-102404959c90)

2024-10-31 07:27 UTC, RileyWen requested changes

2024-10-31 07:27 UTC, RileyWen commented on src/Utilities/PublicHeader/include/crane/Logger.h
> +bool set_Logger_log_level(const std::string mode, spdlog::level::level_enum level);
和其他函数命名风格一致

2024-10-31 07:27 UTC, RileyWen commented on src/Utilities/PublicHeader/include/crane/Logger.h
> +
output parameter用指针 不要用&

2024-10-31 07:27 UTC, RileyWen commented on src/Utilities/PublicHeader/include/crane/Logger.h
> +                const std::string &log_file_pathm,
不要用默认参数

2024-10-31 07:27 UTC, RileyWen commented on src/Utilities/PublicHeader/Logger.cpp
> +bool str_trans_log_level(const std::string str_level, spdlog::level::level_enum &out_Level) {
这命名能不能风格一致点

2024-10-31 15:06 UTC, RileyWen commented on src/Utilities/PublicHeader/include/crane/Logger.h
> +  SPDLOG_LOGGER_TRACE(spdlog::get("default"), __VA_ARGS__)
低效率

2024-10-31 15:07 UTC, RileyWen commented on src/CraneCtld/CraneCtld.cpp
> +        if (!SetLoggerLogLevel("taskscheduler", log_level)) {
每次查 logger 命低效

2024-10-31 15:07 UTC, RileyWen commented on src/CraneCtld/CraneCtld.cpp
> +      if (config["CraneCtldTaskSchedulerLevel"]) {
还是没写成分级形式呀

2024-10-31 15:08 UTC, RileyWen commented on src/CraneCtld/CraneCtld.cpp
> +      if (!StrTransLogLevel(g_config.CraneCtldDebugLevel, &log_level)) {
StrToxxxxx

2024-10-31 15:09 UTC, RileyWen commented on src/CraneCtld/CranedKeeper.h
> +  SPDLOG_LOGGER_TRACE(spdlog::get("cranedkeeper"), __VA_ARGS__)
低效

2024-10-31 15:49 UTC, RileyWen commented on src/Utilities/PublicHeader/Logger.cpp
> +bool SetLoggerLogLevel(const std::string mode, spdlog::level::level_enum level) {
const T 这东西 编译没warning？clang-tidy没提示？这种很基础的问题能不能自己先检查完？？

2024-11-06 06:21 UTC, RileyWen commented on src/Utilities/PublicHeader/include/crane/Logger.h
> +#define CRANECTLD_TRACE(...) SPDLOG_LOGGER_TRACE(GetCtldDefaultLogger(), __VA_ARGS__);
你这东西分了有啥意义吗 cranectd和craned本身就是两个程序啊

2024-11-06 06:21 UTC, RileyWen commented on src/Utilities/PublicHeader/include/crane/Logger.h
> +std::shared_ptr<spdlog::logger> GetCtldCranedKeeperLogger();
这东西直接一个inline变量就完事了 还单独写个函数干啥呢

2024-11-06 06:22 UTC, RileyWen commented on src/Craned/CranedServer.cpp
> +  CRANED_TRACE("Receive TerminateTasks for tasks {}",
这东西统一就叫crane_trace 就好了 不需要分craned和cranectld

2024-11-06 06:25 UTC, RileyWen commented
/etc 样例文件也没改呀

2024-11-11 07:30 UTC, Nativu5 requested changes

2024-11-11 07:34 UTC, RileyWen requested changes

2024-11-11 07:34 UTC, RileyWen commented on src/Craned/CranedPublicDefs.h
> +  std::unordered_map<std::string, spdlog::level::level_enum> logLevels;
?

2024-11-11 07:34 UTC, RileyWen commented on src/Utilities/PublicHeader/include/crane/Logger.h
> +        auto logger = spdlog::get(logger_name); \
说了n遍logger访问不要查map 怎么还在查map

2024-11-11 07:37 UTC, Nativu5 commented on src/Utilities/PublicHeader/Logger.cpp
> +        // 初始化 spdlog
中文注释？

2024-11-11 07:38 UTC, Nativu5 commented on src/Utilities/PublicHeader/include/crane/Logger.h
> +        return nullptr;  // 未找到插件则返回 nullptr
同上

2024-11-13 09:34 UTC, 1daidai1 commented
前端 https://github.com/PKUHPC/CraneSched-FrontEnd/pull/203

2024-11-13 09:54 UTC, 1daidai1 commented
#332

2024-11-13 10:44 UTC, Nativu5 requested changes

2024-11-13 10:44 UTC, Nativu5 commented on etc/config.yaml
> +#Logging Leve
这里的注释怎么不完整呢？另外麻烦按照规范写注释。

2024-11-13 10:44 UTC, Nativu5 commented on protos/Crane.proto
> +  /* RPCs called from logger */
Logger 是一个命令吗？为什么会有一个 `from logger`?
如果要用 ccontrol 去修订 logging level，那应该是 called from ccontrol。

2024-11-13 10:44 UTC, Nativu5 commented on src/CraneCtld/CraneCtld.cpp
> +                for (const auto& levelNode : loggerNode.second) {
这一堆 For 循环有什么必要吗？既然是 Ctld 那直接读 config["Logger"]["CraneCtld"] 不行吗？

2024-11-13 10:44 UTC, Nativu5 commented on etc/config.yaml
> +    Default: trace
所以这个地方的意思是下面这个吗？
```
Logger:
  <Component Name>: 
    <Module Name>: <Logging Level>
```

2024-11-13 12:19 UTC, RileyWen commented
这块别写了 这块越写越多 但是代码里合并标准差的太远了 要合并我们基本得重写 别花时间在这上面了

2024-11-16 17:47 UTC, RileyWen commented
最基础的多线程加锁也不加

2024-11-29 11:06 UTC, closed without merging