TLS/SSL Security Framework
PKUHPC/CraneSched pull request #349
Opened 2024-11-06 07:17 UTC by huerni

2024-11-06 11:37 UTC, Nativu5 commented on .gitignore
> +build/
gitignore 有一些重复的条目

2024-11-06 11:41 UTC, Nativu5 requested changes

2024-11-06 11:41 UTC, Nativu5 commented on dependencies/cmake/CMakeLists.txt
> +# add_subdirectory(nlohmann_json)
这个依赖不能去掉

2024-11-06 11:41 UTC, Nativu5 commented on protos/PublicDefs.proto
> +  string password = 3;
🤔 明文？

2024-11-06 11:41 UTC, Nativu5 commented on src/CraneCtld/CraneCtld.cpp
> +#include "CtldForCranedServer.h"
Precompiled header comes first!

2024-11-06 11:41 UTC, Nativu5 commented on src/CraneCtld/CraneCtld.cpp
> +#include <memory>
CtldPreCompiledHeader.h 中应该有了

2024-11-07 01:18 UTC, huerni commented on .gitignore
> +build/
这个commit暂时的，后面不会推上来

2024-11-07 01:18 UTC, huerni commented on dependencies/cmake/CMakeLists.txt
> +# add_subdirectory(nlohmann_json)
这个也在想怎么解决

2024-11-07 01:24 UTC, huerni commented on protos/PublicDefs.proto
> +  string password = 3;
有SSL的话，前端加密应该没必要了吧

2024-11-19 01:01 UTC, RileyWen commented on protos/PublicDefs.proto
> +  string password = 3;
SSL不一定强制启用 可能还是考虑Hash 存储再加一个Salt

2024-11-19 01:03 UTC, RileyWen commented on src/CraneCtld/CtldForCforedServer.cpp
*Server和CranedKeeper 统一移到RpcService的子文件夹下吧

2024-11-19 01:05 UTC, RileyWen commented on src/Utilities/PublicHeader/GrpcHelper.cpp
> +      char token[iter->second.size()];
C++里面就别写C系风格了吧

2024-11-19 01:17 UTC, huerni commented on src/Utilities/PublicHeader/GrpcHelper.cpp
> +      char token[iter->second.size()];
只能这样，直接转为string的话会出bug

2024-11-19 06:29 UTC, huerni commented on src/Utilities/PublicHeader/GrpcHelper.cpp
> +      char token[iter->second.size()];
不对，好像也是可以用string操作的

2024-12-03 09:29 UTC, huerni commented on protos/PublicDefs.proto
> +  string password = 3;
@RileyWen @Nativu5 @L-Xiafeng 密码这块感觉还得对一下  今天马老师说集群已经认证过账号密码了，所以鹤思本身不需要密码，直接clogin获取token即可。现在的实现是clogin通过uid和密码登录（密码可为空），所以目前的安全框架是否需要对鹤思系统加入密码，保留现在的实现？还是说现在不需要密码，只依赖集群认证登录？

2024-12-03 10:06 UTC, Nativu5 commented on protos/PublicDefs.proto
> +  string password = 3;
这个应该还是需要的：
1. 之前的规划中有提到前端在客户主机而不只是在登录节点上，那么自然需要密码；
2. 从 JWT 的原理来讲，如果调用 clogin 传递 UID 就能使服务端签发 JWT，那么冒充者可以直接仿造一个 clogin 请求，传递一个受害者的 UID 来拿到 JWT。此时 JWT 防冒充的作用就完全失效了。

2024-12-04 01:53 UTC, huerni commented on protos/PublicDefs.proto
> +  string password = 3;
确实是的

2025-02-16 06:21 UTC, L-Xiafeng commented
这个PR是不是废弃了？

2025-02-17 03:25 UTC, huerni commented
> 这个PR是不是废弃了？

是的，新分支在https://github.com/PKUHPC/CraneSched/pull/420

2025-02-17 03:33 UTC, closed without merging