Add specific reasons for failed task submission
PKUHPC/CraneSched pull request #375
Opened 2024-11-26 14:38 UTC by 1daidai1

2024-11-27 05:10 UTC, Nativu5 commented on src/CraneCtld/TaskScheduler.h
> +};
可不可以考虑用 std::expected 或者 cppresult 库？可能需要修改一点逻辑。

2024-11-27 05:37 UTC, 1daidai1 commented on src/CraneCtld/TaskScheduler.h
> +};
好的

2024-11-28 16:33 UTC, RileyWen commented on src/CraneCtld/TaskScheduler.cpp
> +result::result<void, std::pair<CraneErr, std::string>>
？？？？？？？？？？？？？？？？？？

2024-11-29 01:44 UTC, 1daidai1 commented on src/CraneCtld/TaskScheduler.cpp
> +result::result<void, std::pair<CraneErr, std::string>>
返回错误以及具体原因

2024-11-29 11:03 UTC, RileyWen commented
这块之前特意就写的不用string了 一边在errcode化 怎么这边还开始返祖了

2024-11-29 12:55 UTC, 1daidai1 commented
![image](https://github.com/user-attachments/assets/3e10da23-2613-4340-bccb-f9212e649666)
马老师觉得提示不够详细要我修改下

2024-11-29 13:02 UTC, 1daidai1 commented
如果不想这么改的话那我多增加几个枚举值吧，将参数错误这个枚举细化多几个枚举值

2024-12-10 08:38 UTC, 1daidai1 commented
前端：https://github.com/PKUHPC/CraneSched-FrontEnd/pull/218

2024-12-11 05:32 UTC, Nativu5 commented
先基于 Master 分支 rebase 一下吧。

2024-12-12 02:20 UTC, RileyWen commented on src/Utilities/PublicHeader/include/crane/PublicHeader.h
> +const std::unordered_map<crane::grpc::ErrCode, std::string_view> ErrCodeStrMap = {
ERR_INVALID_UID这边开始整体offset改小 然后用array存 做成直接寻址查找

2024-12-19 05:57 UTC, 1daidai1 commented
代码已提交

2025-01-21 10:31 UTC, RileyWen commented on src/CraneCtld/AccountManager.cpp
> +    CRANE_ERROR("time-limit reached the user's limit");
这不是error 然后报错信息太模糊

2025-01-21 10:33 UTC, RileyWen commented on src/CraneCtld/TaskScheduler.cpp
> +    if (!ok) return std::unexpected(crane::grpc::ErrCode::ERR_INVAILD_NODE_LIST);
这边为啥不用using的那个alias

2025-01-21 10:34 UTC, RileyWen commented on src/Utilities/PublicHeader/include/crane/PublicHeader.h
> +        "You are not a user of Crane",
每隔10行空行并注释offset

2025-02-16 06:33 UTC, L-Xiafeng reviewed
原来的Reason是给用户直接看的，现在改成日志之后都修改一下

2025-02-16 06:33 UTC, L-Xiafeng commented on src/CraneCtld/TaskScheduler.cpp
> +CraneExpected<void> TaskScheduler::AcquireTaskAttributes(TaskInCtld* task) {
这里为什么改成CraneExpected

2025-02-16 06:33 UTC, L-Xiafeng commented on src/CraneCtld/CtldGrpcServer.cpp
> +          CRANE_ERROR("Account '{}' is not in your account list", task->account);
日志是写给管理员看的，不是给用户的，改一下文字。

2025-02-16 06:33 UTC, L-Xiafeng commented on src/CraneCtld/AccountManager.cpp
> +    CRANE_ERROR("Unknown user {}", user);
日志重写下

2025-02-16 06:33 UTC, L-Xiafeng commented on src/CraneCtld/AccountManager.cpp
> +        CRANE_ERROR(
日志重写下

2025-02-16 06:33 UTC, L-Xiafeng commented on src/CraneCtld/AccountManager.cpp
> +      CRANE_ERROR("Partition is not allowed for this user");
日志重写下

2025-02-20 03:21 UTC, L-Xiafeng commented
上面提到的所有日志都改一下
1. 信息不够，看不出来在说什么
2. 这些都是原来给用户的报错信息，不适合直接改成日志信息

2025-02-20 03:22 UTC, L-Xiafeng requested changes
上面提到的所有日志都改一下

信息不够，看不出来在说什么
这些都是原来给用户的报错信息，不适合直接改成日志信息

2025-02-22 14:28 UTC, RileyWen commented on protos/PublicDefs.proto
> +  ERR_USER_ALLOWED_ACCOUNT = 7;  // User does not have permission for the account
这错误码再换个好懂些的命名

2025-02-22 14:47 UTC, RileyWen commented on protos/PublicDefs.proto
> +  ERR_INVALID_PARENTACCOUNT = 13;  // Invalid parent account
PARENTACCOUNT 下划线

2025-02-22 14:47 UTC, RileyWen commented on protos/PublicDefs.proto
> +  ERR_DELETE_ACCOUNT = 14;   // Account has child nodes
1

2025-02-22 14:48 UTC, RileyWen commented on protos/PublicDefs.proto
> +  ERR_DUPLICATE_ACCOUNT = 12;  // Duplicate account insertion
1

2025-02-22 14:49 UTC, RileyWen commented on protos/PublicDefs.proto
> +  ERR_PARENT_ALLOWED_PARTITION = 19; // Parent account does not include this partition
这错误原因啥意思

2025-02-22 14:53 UTC, RileyWen commented on src/Utilities/PublicHeader/include/crane/PublicHeader.h
> +        "Child has partition error",
@1daidai1 叫你检查来检查去 这报错你检查这么多检查了个啥？？？？？？？？？？ 这句子你自己能读懂？？？？？？？？？

2025-02-22 14:54 UTC, RileyWen commented on protos/PublicDefs.proto
> +  ERR_CHILD_HAS_PARTITION = 21; // Partition '{}' is used by some descendant node of the account '{}'. Ignoring this constraint with forced operation.
@huerni 这错误原因啥意思

2025-02-22 14:56 UTC, RileyWen commented on protos/PublicDefs.proto
> +  ERR_CONVERT_TO_INTERGER = 27;  // String to integer conversion failed
拼写错误

2025-02-22 15:20 UTC, RileyWen commented on src/Utilities/PublicHeader/include/crane/PublicHeader.h
> +        "No available node"
@1daidai1 叫你对了半天代码 怎么对了这么多遍还是有个东西对漏了？？？？？？？？？？你这活都是在敷衍了事吗？？？

2025-02-22 15:22 UTC, RileyWen commented on src/Utilities/PublicHeader/include/crane/PublicHeader.h
> +        "No available node"
天天问就是写完了 怎么查个五六七八遍还是有会导致程序崩溃严重的问题呢

2025-02-22 15:28 UTC, RileyWen commented on protos/PublicDefs.proto
> +  ERR_CHILD_HAS_DEFAULT_QOS = 35; // Someone is using QoS '{}' as default QoS. Ignoring this constraint with forced deletion, the deleted default QoS is randomly replaced with one of the remaining it
@huerni 把代码注释这边的{}去掉

2025-02-22 15:34 UTC, RileyWen commented on protos/PublicDefs.proto
> +  ERR_USER_ALLOWED_ACCOUNT = 7;  // User does not have permission for the account
@huerni

2025-02-22 15:36 UTC, RileyWen commented on src/CraneCtld/TaskScheduler.cpp
> +CraneExpected<void> TaskScheduler::AcquireTaskAttributes(TaskInCtld* task) {
就是错误码统一了吧 感觉也没啥

2025-02-24 01:53 UTC, huerni commented on protos/PublicDefs.proto
> +  ERR_USER_DUPLICATE_ACCOUNT= 6;  // User duplicate account insertion
向账户插入已有用户的时候报错

2025-02-27 08:27 UTC, L-Xiafeng commented on protos/PublicDefs.proto
> +  ERR_CODE_COUNT  = 67;
__ERR_CODE_COUNT

2025-02-27 14:25 UTC, L-Xiafeng approved these changes

2025-02-27 14:29 UTC, merged