Add a remote call for task completion for plugins running on craned
PKUHPC/CraneSched pull request #378
Opened 2024-12-01 10:32 UTC by huyongqii

* Add a remote call for task completion for plugins running on craned. 
* Modify the method for task requesting device permission access.

2024-12-01 11:02 UTC, L-Xiafeng requested changes

2024-12-01 11:02 UTC, L-Xiafeng commented on src/Utilities/PluginClient/PluginClient.cpp
> +                                        const std::string& task_name) {
这里参数是task name吗？好像和caller的含义不太一样

2024-12-01 11:02 UTC, L-Xiafeng commented on src/Utilities/PluginClient/include/crane/PluginClient.h
> +    CRANED_START,
可以改成cgroup create/destroy

2024-12-01 11:02 UTC, L-Xiafeng commented on src/Utilities/PluginClient/include/crane/PluginClient.h
> +    CRANED_START,
其他的可以加一个对应的前缀，job start...这类

2024-12-01 11:30 UTC, huyongqii commented on src/Craned/CgroupManager.cpp
>  bool CgroupV1::SetDeviceAccess(const std::unordered_set<SlotId> &devices,
这种方法写法可能需要讨论下，改动的原因是：原先方法会默认任务可以访问所有设备，这样通过读取device.list文件，不好知道任务绑定了哪些GPU设备，即使任务没有绑定GPU，也会有访问所有GPU的权限。修改成这种白名单的方法，只会赋予任务通过--gres指定的设备和一些默认的设备，这样的话，插件端可以通过读取device.list文件获得有权访问的GPU设备。插件端也可以不用通过RPC来获取任务绑定的GPU设备，可以直接读取文件获得。
我们可以再讨论看看使用哪种方法更好些

2024-12-01 11:33 UTC, huyongqii commented on src/Utilities/PluginClient/PluginClient.cpp
> +                                        const std::string& task_name) {
原先JobMonitor传递的是task_id和cgroup，实际cgroup的值也是task_name并非任务cgroup路径，因为cgroup的系统路径固定，不需要传递，所以这里改成了task_name

2024-12-01 11:37 UTC, huyongqii commented on src/Utilities/PluginClient/include/crane/PluginClient.h
> +    CRANED_START,
之前跟永坤讨论了下，觉得这边可以改为一个通用的接口，我这边稍微更改了下以满足目前的能耗搜集插件，后续如果永坤重构的话，可以更加完善些

2024-12-01 11:57 UTC, L-Xiafeng commented on src/Utilities/PluginClient/include/crane/PluginClient.h
> +    CRANED_START,
那这个也先改成cgroup create

2024-12-01 12:02 UTC, huyongqii commented on src/Utilities/PluginClient/include/crane/PluginClient.h
> +    CRANED_START,
可以的

2024-12-01 12:07 UTC, huyongqii commented on src/Utilities/PluginClient/PluginClient.cpp
> +                                        const std::string& task_name) {
Crane_Task_38 这种形式的在的项目叫task_name么，这里的task_name是“Crane_Task_” + task_id组成的

2024-12-01 12:08 UTC, L-Xiafeng commented on src/Utilities/PluginClient/PluginClient.cpp
> +                                        const std::string& task_name) {
系统里面task是有id也有name的，这里重了

2024-12-01 12:20 UTC, huyongqii commented on src/Utilities/PluginClient/PluginClient.cpp
> +                                        const std::string& task_name) {
不太理解这里重了的意思，我看TaskInfo里是有name这个字段的
不过`bool CgroupManager::AllocateAndGetCgroup(task_id_t task_id,
                                         CgroupInterface **cg)` 这里传递的是uint32_t类型的task_id，所以调用的`g_plugin_client->StartCranedHookAsync(task_id,
                                          CgroupConstant::kTaskCgPathPrefix +
                                              std::to_string(task_id))`时，这里通过前缀和task_id构成的这里的task_name，kTaskCgPathPrefix的实际值是"Crane_Task_"

2024-12-01 15:39 UTC, L-Xiafeng commented on src/Utilities/PluginClient/PluginClient.cpp
> +                                        const std::string& task_name) {
这个参数不该叫task name，应该是taskcgroupname之类的

2024-12-02 02:49 UTC, huyongqii commented on src/Utilities/PluginClient/PluginClient.cpp
> +                                        const std::string& task_name) {
好的，已修改

2024-12-02 16:13 UTC, L-Xiafeng commented on src/Craned/CgroupManager.cpp
>  bool CgroupV1::SetDeviceAccess(const std::unordered_set<SlotId> &devices,
可以改一下plugin的grpc，把任务的一些信息在hook里传过去，感觉这个是必要的

2024-12-03 07:48 UTC, huyongqii commented on src/Craned/CgroupManager.cpp
>  bool CgroupV1::SetDeviceAccess(const std::unordered_set<SlotId> &devices,
好的，目前方法已改回。获取任务绑定GPU还是改成了RPC发送request devices，插件端再提取绑定的GPU的方法

2024-12-03 07:48 UTC, huyongqii commented on protos/Plugin.proto
> +  rpc DestroyCgroupHook(DestroyCgroupHookRequest) returns (DestroyCgroupHookReply);
OK

2024-12-03 12:15 UTC, RileyWen commented on protos/Plugin.proto
> +  repeated string devices = 3;
这边看看能不能换成对应proto的ResourceView结构体

2024-12-03 12:16 UTC, RileyWen commented
其他我目前没啥问题

2024-12-03 16:13 UTC, huyongqii commented on protos/Plugin.proto
> +  repeated string devices = 3;
`message ResourceView {
  AllocatableResource allocatable_res = 1;
  DeviceMap device_map = 2;
}`
`message DedicatedResourceInNode {
  map<string /*device name*/, DeviceTypeSlotsMap> name_type_map = 1;
}`
目前ResourceView里的没有能直接将DedicatedResourceInNode转换成DeviceMap的函数，需要添加一下
所以感觉可以直接传递DedicatedResourceInNode这个proto也可以

2024-12-04 15:51 UTC, RileyWen commented on src/Craned/CgroupManager.cpp
> +    g_plugin_client->CreateCgroupHookAsync(task_id,
这个地方要check一下 V1 和 V2是否都能work

2024-12-04 15:51 UTC, RileyWen commented on src/Craned/CgroupManager.cpp
> +        InitializeController_(
这个地方要check一下 V1 和 V2是否都能work

2024-12-05 02:57 UTC, huyongqii commented on src/Craned/CgroupManager.cpp
> +        InitializeController_(
v2 blkio整合到了io控制器上，`Taoran Wang` 应该已经测试过了

2024-12-05 18:19 UTC, RileyWen commented on src/Utilities/PluginClient/PluginClient.cpp
> +  auto request = dynamic_cast<CreateCgroupHookRequest*>(msg);
类型改成`auto *`，然后dynamic_cast 有可能为空指针，加个`CRANE_ASSERT(request != nullptr);`这样的语句

2024-12-05 18:19 UTC, RileyWen commented on src/Utilities/PluginClient/PluginClient.cpp
> +  auto request = dynamic_cast<DestroyCgroupHookRequest*>(msg);
auto *

2024-12-06 05:29 UTC, huyongqii commented on src/Utilities/PluginClient/PluginClient.cpp
> +  auto request = dynamic_cast<CreateCgroupHookRequest*>(msg);
好的，已完善

2024-12-06 06:23 UTC, Nativu5 commented
LGTM. 可以准备合并了。

2024-12-06 06:23 UTC, Nativu5 approved these changes

2024-12-06 06:27 UTC, L-Xiafeng approved these changes

2024-12-06 06:29 UTC, merged