Fix gid val error
PKUHPC/CraneSched pull request #390
Opened 2024-12-10 02:17 UTC by 1daidai1

https://private-user-images.githubusercontent.com/166272788/394078620-afbfadce-68e7-4d99-b373-dfe5fd9f5721.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3OTczMjgsIm5iZiI6MTczMzc5NzAyOCwicGF0aCI6Ii8xNjYyNzI3ODgvMzk0MDc4NjIwLWFmYmZhZGNlLTY4ZTctNGQ5OS1iMzczLWRmZTVmZDlmNTcyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMFQwMjE3MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MTQzZjk1YjFjYWI3MzBhOTlkMzA0MDI1MzlmZjkxNjljMTA1ZWU4MzY4Nzk2ZjgwMWQ3Y2QxNzdmMmRlM2M4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6pljwVRjqw1WZxR8KVJS4FjLiW6NIeoZXbSf492w_o0

2024-12-10 02:18 UTC, 1daidai1 commented
前端https://github.com/PKUHPC/CraneSched-FrontEnd/pull/217

2024-12-11 04:49 UTC, Nativu5 requested changes

2024-12-11 04:49 UTC, Nativu5 commented on src/CraneCtld/CtldGrpcServer.cpp
> +  task->SetGid(task->Gid());
为什么在这里做？不应该是在这里吗？https://github.com/PKUHPC/CraneSched/blob/d85f41ac389ae0270c2601d42d90c1456a443ae8/src/CraneCtld/CtldPublicDefs.h#L474

2024-12-11 11:22 UTC, Nativu5 commented
GID 的修改问题比较多，需要后续讨论。

2024-12-11 11:22 UTC, closed without merging