Dev/partition allow accounts
PKUHPC/CraneSched pull request #404
Opened 2024-12-19 08:58 UTC by huerni

1. config文件partition添加AllowAccounts设置，AllowAccounts=，ctld启动时读取配置。
2. 命令行修改partition的AllowAccounts，无需持久化，持久化只能在config文件进行定义。
3. ccontrol show partition 添加AllowAccounts条目展示。
4. 提交任务时判断account是否在partition的AllowAccounts中

2025-01-16 03:01 UTC, RileyWen requested changes

2025-01-16 03:01 UTC, RileyWen commented on src/CraneCtld/CtldGrpcServer.cpp
> +  result = g_account_manager->CheckModifyPartitionAllowAccounts(
错误处理

2025-01-16 03:01 UTC, RileyWen commented on src/CraneCtld/CtldGrpcServer.cpp
> +  if (!g_meta_container->CheckIfAccountIsAllowedInPartition(task->partition_id,
这地方有问题吧

2025-02-13 12:34 UTC, L-Xiafeng commented on src/CraneCtld/AccountManager.cpp
>  AccountManager::CraneExpected<void>
AccountManager::CraneExpected<void>
换成CraneExpected

2025-02-18 05:59 UTC, huerni commented on src/CraneCtld/AccountManager.cpp
>  AccountManager::CraneExpected<void>
代老师那边错误码分支这里还有CheckUidIsAdmin都改了吧，这里就不用改了

2025-02-18 06:40 UTC, huerni commented on src/CraneCtld/CranedMetaContainer.cpp
> +      return std::unexpected(
改成错误码那要改的太多了，等 https://github.com/PKUHPC/CraneSched/pull/375 改完合并再改吧

2025-02-18 06:59 UTC, L-Xiafeng commented on src/CraneCtld/AccountManager.cpp
>  AccountManager::CraneExpected<void>
ok

2025-02-18 06:59 UTC, L-Xiafeng commented on src/CraneCtld/CranedMetaContainer.cpp
> +      return std::unexpected(
可以

2025-02-18 06:59 UTC, L-Xiafeng commented
需要@RileyWen approve

2025-02-18 07:00 UTC, L-Xiafeng approved these changes

2025-02-24 03:41 UTC, RileyWen commented
#375 等这个PR合并后Rebase 然后合并

2025-02-28 03:06 UTC, huerni commented
已review，rebase完毕，交由 @Zhouhao3290 周老师测试

2025-02-28 03:18 UTC, RileyWen commented on etc/config.yaml
> +    DeniedAccounts: ac1, ac2
这两个不是互斥的吗

2025-02-28 03:20 UTC, huerni commented on etc/config.yaml
> +    DeniedAccounts: ac1, ac2
是的，设置了AllowedAccounts，DeniedAccounts不起作用

2025-02-28 03:35 UTC, RileyWen commented on src/CraneCtld/CranedMetaContainer.cpp
> +  if (!part_metas_map->contains(partition_name)) {
contains  和 at查了两次 用find

2025-02-28 03:35 UTC, RileyWen commented on src/CraneCtld/CranedMetaContainer.cpp
> +  auto part_meta = part_metas_map->at(partition_name).GetExclusivePtr();
用find 的iter

2025-02-28 03:36 UTC, RileyWen commented on src/CraneCtld/CranedMetaContainer.cpp
> +    const auto& denied_accounts =
先查empty

2025-02-28 03:36 UTC, RileyWen commented on src/CraneCtld/CranedMetaContainer.cpp
> +  if (!allowed_accounts.empty()) {
一行&&就行了 不用两个if

2025-02-28 03:40 UTC, RileyWen commented on src/CraneCtld/CranedMetaContainer.cpp
> +    const std::unordered_set<std::string>& accounts) {
这边可以弄成右值初始化

2025-02-28 03:45 UTC, RileyWen commented on protos/Crane.proto
> +  string partition_name = 2;
partition

2025-02-28 03:46 UTC, RileyWen commented on protos/Crane.proto
> +  bool is_modify_allowed = 3;
is_modifying_allowed

2025-02-28 03:48 UTC, RileyWen commented on protos/Crane.proto
> +  uint32 uid = 1;
ModifyPartitionAllowedOrDeniedAccounts 这个统一改成ModifyPartitionAcl吧
Acl就是Access Control List

2025-02-28 03:49 UTC, RileyWen commented on protos/Crane.proto
> +  uint32 uid = 1;
原来名称太太长了

2025-02-28 07:06 UTC, huerni commented on src/CraneCtld/CranedMetaContainer.cpp
> +  if (!allowed_accounts.empty()) {
合起来逻辑变了

2025-02-28 07:17 UTC, L-Xiafeng commented on etc/config.yaml
> +    DeniedAccounts: ac1, ac2
这个默认注释掉比较好吧

2025-03-04 08:50 UTC, L-Xiafeng approved these changes

2025-03-04 08:51 UTC, RileyWen commented
这还有conflict rebase下

2025-03-04 08:52 UTC, RileyWen commented on protos/PublicDefs.proto
> +  ERR_ALLOWEDLIST_MISSING = 67;  // The current account is not in the allowed account list for the partition.
ERR_NOT_IN_ALLOWED_LIST

2025-03-04 08:53 UTC, RileyWen commented on protos/PublicDefs.proto
> +  ERR_DENYLIST_HIT = 68;  // The current account has been explicitly added to the deny list for the partition.
ERR_IN_DENIED_LIST

2025-03-04 08:53 UTC, RileyWen commented on protos/PublicDefs.proto
> +  __ERR_CODE_COUNT = 69;
这个在新的PR里删掉了 Rebase下

2025-03-04 08:54 UTC, RileyWen commented on src/CraneCtld/CranedMetaContainer.cpp
> +    auto* allowed_accounts = part_info->mutable_allowed_accounts();
这东西有权限问题吗？

2025-03-05 02:16 UTC, RileyWen submitted a review, later dismissed

2025-03-05 02:35 UTC, L-Xiafeng commented
加一个同时有allowed和denied配置的warning吧

2025-03-05 03:19 UTC, huerni commented
> 加一个同时有allowed和denied配置的warning吧

行，前端有，后端读取config这边我也加一个吧

2025-03-05 06:59 UTC, RileyWen approved these changes

2025-03-05 07:57 UTC, merged