fix cacct priority val error
PKUHPC/CraneSched pull request #414
Opened 2024-12-27 07:30 UTC by 1daidai1

2024-12-27 07:38 UTC, 1daidai1 commented
前端https://github.com/PKUHPC/CraneSched-FrontEnd/pull/230

2024-12-31 14:53 UTC, RileyWen commented on src/CraneCtld/TaskScheduler.cpp
> +    g_embedded_db_client->UpdateTaskToCtldIfExists(0, task->TaskDbId(),
这行代码不该加 删了

2024-12-31 14:54 UTC, RileyWen commented on src/CraneCtld/TaskScheduler.cpp
> +    task->MutableTaskToCtld()->set_priority(priority);
调度里面的代码都删了

2024-12-31 14:57 UTC, RileyWen commented on protos/PublicDefs.proto
> +  uint32 priority = 14;
提交的时候哪来的优先级

2025-01-02 01:51 UTC, 1daidai1 commented on protos/PublicDefs.proto
> +  uint32 priority = 14;
加这个的目的是考虑突然掉电情况下恢复任务running和completed任务没有存在mongodb中，恢复过来优先级变成零的情况，没有保存最后一次的优先级

2025-02-13 03:36 UTC, RileyWen requested changes

2025-02-13 03:36 UTC, RileyWen commented on src/CraneCtld/TaskScheduler.cpp
> +      task->SetPriority(task->cached_priority);
地方加错了

2025-02-23 08:44 UTC, merged